### ISSUE TITLE
sampling negative samples

### ISSUE THREAD

**Issue by Karthik-Jayasurya** [LaceyChen17/DREAM#1]
In the bpr_loss function, the neg_idx seems to be a random sample of 'all' the items instead of just the set of negative items. Why not just sample from the negative item set? Is this approximation done for performance reasons? 

The code looks great & simple at the same time to understand. Keep up the good work!

**Comment by yihong-chen** [comment]
Thank you for the advice^_^ Using random samples from all the item is just for coding convenience. I think you are right that better performance can be achieved if we just sample sample from the negative item set. (But as for the instacart dataset, it makes little difference as the negative item set is almost as big as the whole item set for most of the users)
