### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by Gbau08** [LaceyChen17/DREAM#3]
Hello Yihong,

I was able to run your model after a few modification, great work, and the coding is propper and can be nicely understood. I see in your other repo that you implemented evaluation metrics such as F1 score based on recall and precision. Do you have that for DREAM as well?

Furthermore, are the choice of your parameters random (clip, learning rate...) or did you do a grid search ?

Thanks again!

**Comment by yihong-chen** [comment]
Actually, I implemented Dream for the instacart market analysis completition. So the evaluation metrics are also based on the instacart dataset. I think the following functions are helpful to you
![image](https://user-images.githubusercontent.com/11754923/37238182-e23808dc-245b-11e8-98da-97e66880c728.png)

As for the parameters, I did a gird search, or rather babysit tuning. 

I hope these would help you
