### ISSUE TITLE
Data dont converge (Loss going up and down)

### ISSUE THREAD

**Issue by Crosswar** [LaceyChen17/DREAM#4]
Hello,

I downloaded this network and im trying to run with the base dataset from Instacart, and the data doesnt seem to converge, and goes nowhere. Loss keeps going up and down, i tried changing the LR from 0.1 to 0.0001 and alternate the optimizers but nothing seems to work. I wanted to simulate the instacart output to start working on the dream from there.

If you guys have any insights, would be helpful, thanks

**Comment by yihong-chen** [comment]
How many epochs did you train for ?  Could you post the training curve ? Hyper-param tuning in deep learning could sometimes be frustrating. Here is one of my previous training logs.(I have to say it is lucky that I didn't delete them). Hope it would help you. 
[lstm_clip20.log](https://github.com/LaceyChen17/DREAM/files/1963665/lstm_clip20.log)

**Comment by Crosswar** [comment]
I was using 100 Epochs for 80-250 Batch Size considering the whole instacart dataset size. 
Here's my constants: 
`DREAM_CONFIG = {'basket_pool_type': 'max', # 'avg'
                'rnn_layers': 3, # 2, 3
                'rnn_type': 'LSTM',#'RNN_TANH',#'GRU',#'LSTM',# 'RNN_RELU',
                'dropout': 0.5,
                # 'num_product': 49688 + 1, # padding idx = 0
                'num_product': 49688 + 1 + 1, 
                # 49688 products, padding idx = 0, none idx = 49689, none idx indicates no products
                'none_idx': 49689,
                'embedding_dim': 128, # 128 
                'cuda': False, # True,
                'clip': 0.25, # 0.25
                'epochs': 100,
                'batch_size': 100,
                'learning_rate': 0.0001, # 0.0001
                'log_interval': 1, # num of batchs between two logging
                'checkpoint_dir': DREAM_MODEL_DIR + 'reorder-next-dream-{epoch:02d}-{loss:.4f}.model',
                }`

I also uncommented the line of code for replacement:

train.py /74 and 102
`neg = random.sample(range(1, config.num_product), len(basket_t)) # without replacement`

**Comment by Crosswar** [comment]
![dream](https://user-images.githubusercontent.com/1023135/39474984-c5ace35a-4d2c-11e8-9c1c-27081ac9c2a6.jpeg)

I got here so far

**Comment by yihong-chen** [comment]
The loss is going down. It seems OK with your training.

**Comment by Crosswar** [comment]
Yeah, this is tonights results. I changed the LSTM to RNN_RELU and increased the batch to 100 and Learning Rate to 0.0001. IT seems to be going somewhere.
Im running with your setup right now

**Comment by Crosswar** [comment]
![image](https://user-images.githubusercontent.com/1023135/39488938-45162ef8-4d5a-11e8-93f3-7ffbe235ec72.png)

still not going anywhere. 250 batches later, still on 22 Loss

**Comment by yihong-chen** [comment]
Did you try the hyper-params given in my attached log？

在 2018年5月2日，上午3:11，Gabriel <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://user-images.githubusercontent.com/1023135/39488938-45162ef8-4d5a-11e8-93f3-7ffbe235ec72.png>

still not going anywhere. 250 batches later, still on 22 Loss

**Comment by Crosswar** [comment]
Still running (4 hours):
![image](https://user-images.githubusercontent.com/1023135/39500178-03584f30-4d89-11e8-9819-373be32b09a1.png)

**Comment by Crosswar** [comment]
Its on 0.6 to 0.9 since batch 130, give or take.
With these parameters:

> DREAM_CONFIG = {'basket_pool_type': 'max', # 'avg'
                'rnn_layers': 2, # 2, 3
                'rnn_type': 'LSTM',#'RNN_TANH',#'GRU',#'LSTM',# 'RNN_RELU',
                'dropout': 0.5,
                # 'num_product': 49688 + 1, # padding idx = 0
                'num_product': 49688 + 1 + 1, 
                # 49688 products, padding idx = 0, none idx = 49689, none idx indicates no products
                'none_idx': 49689,
                'embedding_dim': 128, # 128 
                'cuda': False, # True,
                'clip': 20, # 0.25
                'epochs': 10,
                'batch_size': 32,
                'learning_rate': 0.1, # 0.0001
                'log_interval': 1, # num of batchs between two logging
                'checkpoint_dir': DREAM_MODEL_DIR + 'reorder-next-dream-{epoch:02d}-{loss:.4f}.model',
                }

**Comment by yihong-chen** [comment]
I think 0.6 - 0.9 is enough. BTW do you train on GPU ? It seems a bit slow.

**Comment by Crosswar** [comment]
Not at the moment. Im using a Macbook Pro. CPU processing only. 
And it was 06.00 - 09.00, i mistyped the values. After Half epoch it never passed the 05.00-08.00 range.

**Comment by angellicadearaujo** [comment]
Hello, guys.

When trying the above recommended parameters for CUDA TRUE I get an error:

`THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/generated/../THCReduceAll.cuh line=334 error=59 : device-side assert triggered
dropout 0.5
learning_rate 0.1
clip 20
embedding_dim 128
batch_size 32
cuda True
rnn_type LSTM
epochs 10
none_idx 49689
log_interval 1
num_product 49689
checkpoint_dir /home/xxx/xxx/laceychen/Instacart/dream/reorder-next-dream-{epoch:02d}-{loss:.4f}.model
rnn_layers 2
basket_pool_type max
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    train_reorder_dream()
  File "train.py", line 157, in train_reorder_dream
    loss = reorder_bpr_loss(r_baskets, h_baskets, dynamic_user, dr_model.encode.weight, dr_config)
  File "train.py", line 79, in reorder_bpr_loss
    nll_u.append(- torch.mean(torch.nn.LogSigmoid()(score)))
  File "/home/xxx/anaconda3/envs/dream/lib/python3.5/site-packages/torch/autograd/variable.py", line 443, in mean
    return Mean(dim)(self)
  File "/home/xxx/anaconda3/envs/dream/lib/python3.5/site-packages/torch/autograd/_functions/reduce.py", line 16, in forward
    return input.new((fn(),))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /b/wheel/pytorch-src/torch/lib/THC/generated/../THCReduceAll.cuh:334
/b/wheel/pytorch-src/torch/lib/THC/THCTensorIndex.cu:275: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 1, SrcDim = 1, IdxDim = -2]: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
`
When reverting for the original parameters, model comes to run again with no errors.
`DREAM_CONFIG = {'basket_pool_type': 'max', # 'avg'
                'rnn_layers': 2, # 2, 3
                'rnn_type': 'LSTM',#'RNN_TANH',#'GRU',#'LSTM',# 'RNN_RELU',
                'dropout': 0.5,
                # 'num_product': 49688 + 1, # padding idx = 0
                'num_product': 49688 + 1 + 1,
                # 49688 products, padding idx = 0, none idx = 49689, none idx indicates no products
                'none_idx': 49689,
                'embedding_dim': 64, # 128
                'cuda': True, # True,
                'clip': 20, # 0.25
                'epochs': 100,
                'batch_size': 256,
                'learning_rate': 0.01, # 0.0001
                'log_interval': 1, # num of batchs between two logging
                'checkpoint_dir': DREAM_MODEL_DIR + 'reorder-next-dream-{epoch:02d}-{loss:.4f}.model',
                }`

**Comment by yihong-chen** [comment]
@Crosswar Maybe you could try manual learning rate schedule

**Comment by yihong-chen** [comment]
@angellicacardozo  Could you check if you have out-of-bound indices ? I think the `num_product` should be 49688 + 1 + 1 = 49690

**Comment by Crosswar** [comment]
When i uncomment this line
neg = random.sample(range(1, config.num_product), len(basket_t)) # without replacement

The loss seems to work better, and i can reach 04.90 but it stays there, i coudnt reproduce your log, where you hit 00.80. Im using a manual LR also, but no improvements aswell

**Comment by angellicadearaujo** [comment]
@LaceyChen17 I have downloaded the model code again and it started to run. Maybe I have made some kind of change that have broken it. Thank you anyway.

**Comment by angellicadearaujo** [comment]
Hello, guys.

I've tried the above parameters and I've got some kind of convergence. However, I couldn't get the approximation like @LaceyChen17 did on this .log file. For example:

Yours
> [Training]| Epochs   2 | Batch  2070 /  5156 | ms/batch 1432.03 | Loss 01.15 |

Mine
>[Training]| Epochs   2 | Batch  2070 /  5156 | ms/batch 3964.28 | Loss 07.04 |

@LaceyChen17 ,  the ms/batch parameter has some kind of influence over the above results? Could you help me to understand how does it works with the model?

I still cannot achieve the loss function final result like you have got at your .log file.
> [Training]| Epochs   5 | Batch    39 /  5156 | ms/batch 2011.16 | Loss 00.88 |

Regards,
.

**Comment by yihong-chen** [comment]
The ms/batch is the training speed which depends on your device. The log I provided was the version which  I trained last year on GPU. I haven't tried to train the model on CPU. I'll try to work out whether the device influence the training result or there is some other tuning needed

**Comment by angellicadearaujo** [comment]
Yeah, I am think I am using the GPU for the task... 

> [0] GeForce GTX 1080 Ti | 63'C, 100 % |  3887 / 11177 MB | myuser:python/14624(3777M) 

However the result is still the same

> [Training]| Epochs 2 | Batch 2070 / 5156 | ms/batch 3964.28 | Loss 07.04 |

Can't figure out what is going on. I don't know if it is something about the pytorch version and the cuda.

> Cuda compilation tools, release 8.0, V8.0.61

**Comment by Crosswar** [comment]
@LaceyChen17 Do you have the latest code that you used to execute and generate the models for this DREAM? It seems there is something missing. Even using CUDA and the same constants as you, i cant seem to be any closer to your output. My loss doesnt go below **06.00-08.00** as opposed to your **00.88.** if you can send any other code you have (that you used to run that output you sent), it would be great. 
Thanks

**Comment by yihong-chen** [comment]
@Crosswar Sorry for the late response. I am trying to re-run the code which is the same as the current repo.  My results are similar as you (06-08). I am tuning the hyper-params to see if it could get better. Thank you for report this reproducing issue here.

**Comment by yihong-chen** [comment]
@angellicacardozo  @Crosswar I found a bug in the logging. Actually, the loss reported in the log is batch-level. So it is hard to compare loss when the batch_size is different. I am updating my code to fix this.

**Comment by Crosswar** [comment]
@LaceyChen17 Great! Did you managed to get past 06-08 then? Also we need to uncomment the #Replacement line, right? Line 37/66 now (#Without Replacement)

Did you commit the hyper params? The new set?

**Comment by Crosswar** [comment]
RuntimeError: matrices expected, got 3D, 2D tensors at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:1232

**Comment by Crosswar** [comment]
Im running now, it seems to be working
