### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by paradise94** [LaceyChen17/DREAM#5]
你好，我想跑一下你的程序，但是发现数据集找不到了，麻烦能不能发一份至我的邮箱（328634682@qq.com）。谢谢！

**Comment by yihong-chen** [comment]
I suggest you read the README.md for this repo carefully. I actually provided the link to the dataset in it.

**Comment by paradise94** [comment]
我下载好了，但是数据集里没有.pkl文件

**Comment by yihong-chen** [comment]
I think you do not need pkl to train DREAM model.

**Comment by kaimast** [comment]
I ran into a similar problem. The issue is not the the pkl file is missing (it will be created by the script), but the folder it will be created in does not exist.
