### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by julielin123** [LaceyChen17/DREAM#6]
hi, may i ask a question that how you use train.py to train the model DREAM? i didn`t see any function call the function 
evaluate_reorder_dream().
 i can`t find any entry to use this function to train the model. your answer will helps a lot, thank you!

**Comment by yihong-chen** [comment]
Hi, I think maybe you could check the [line 274-277](https://github.com/LaceyChen17/DREAM/blob/b49fee5c0be7a3fe06b5070aa61e1d8cd53f78b7/src/train.py#L274).

**Comment by julielin123** [comment]
Is there  anything like this? This is what I add.
```
if __name__ == '__main__':
    evaluate_reorder_dream()
```
There are only function definitions in train.py, so I don`t know how to use it.
Besides, I want to ask you that what the function of [repackage_hidden()](https://github.com/LaceyChen17/DREAM/blob/b49fee5c0be7a3fe06b5070aa61e1d8cd53f78b7/src/utils.py#L89) in utils.py.

**Comment by yihong-chen** [comment]
line 1-227 are for function definitions. The main training script starts from [here](https://github.com/LaceyChen17/DREAM/blob/b49fee5c0be7a3fe06b5070aa61e1d8cd53f78b7/src/train.py#L227). You can directly run train.py by runing "python train.py". I do not write the main function and I think it's not necessary.  You could add main function if you like.

In pytorch rnn implementations, repackage_hidden is used to detach the hidden state from previous computational graph. If we do not repackage the hidden state, the entire hidden state would be too large to run after a few training batches.

**Comment by julielin123** [comment]
I`m so sorry to bother you about an error with [line84](https://github.com/LaceyChen17/DREAM/blob/b49fee5c0be7a3fe06b5070aa61e1d8cd53f78b7/src/train.py#L84):

`Traceback (most recent call last):
  File "/home/gly/study/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)

  File "/home/gly/study/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script

  File "/home/gly/lxx/DREAM-master/src/train.py", line 272, in <module>
    train_dream()

  File "/home/gly/lxx/DREAM-master/src/train.py", line 84, in train_dream
    dr_hidden = repackage_hidden(dr_hidden)  # repackage hidden state for RNN

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/lxx/DREAM-master/src/utils.py", line 94, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)

  File "/home/gly/anaconda/lib/python2.7/site-packages/torch/tensor.py", line 360, in __iter__
    raise TypeError('iteration over a 0-d tensor')

TypeError: iteration over a 0-d tensor
`
I do not know why it goes wrong and I am not very familiar with pytorch.

**Comment by yihong-chen** [comment]
I suggest you check the version of pytorch and python. And you'd better learn pytorch first. The official tutorial provides an excellent quickstart.

**Comment by cowarder** [comment]
I guess that's because of the version of your torch. If you install torch by following the official instruction, the version is 0.4.0, there are many differences compared with the previous versions. This page might help:https://github.com/pytorch/pytorch/releases

**Comment by yul091** [comment]
I meet the same question, and I'm sure my torch version is 0.4.0, have you solve this problem?
