### ISSUE TITLE
Market Basket Analysis (MBA) with Apriori or FP-Growth algorithms

### ISSUE THREAD

**Issue by jolasman** [LaceyChen17/DREAM#7]
Hi! I am new to the MBA, and I found your repo. Do you think your DREAM implementation gives better results than the Apriori or FP-Growth algorithm?

Thanks in advance :)

**Comment by yihong-chen** [comment]
I didn't compare DREAM with the frequent set based methods. In terms of the personalized basket prediction, DREAM may be better because the Apriori focuses on the general pattern among all users while DREAM attempts to capture the purchase pattern for individual users.
